# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscribernewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
