# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='views_count',
        ),
    ]
